apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: getvalues-proxy
spec:
  selector:
    app: database-getvalues
  type: NodePort
  #type: ClusterIP
  ports:
    - port: 9099
      targetPort: 8888
      nodePort: 9099
      protocol: TCP
