apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: value-server-proxy
spec:
  selector:
    app: getvalues-database
  type: NodePort
  #type: ClusterIP
  ports:
    - port: 9099
      targetPort: 8888
      nodePort: 9099
      protocol: TCP
